SPOOL log_temp.txt
PROMPT Модуль технолога
PROMPT Создаём таблицу c названием групп технологических операций

CREATE TABLE TCHG_OPERATION_GROUP (
    Group_ID        NUMBER          NOT NULL,
    Group_Name      VARCHAR2(500)   NOT NULL,
    Group_Number    NUMBER          NOT NULL
);

ALTER TABLE TCHG_OPERATION_GROUP
    ADD CONSTRAINT C_Group_ID_PK PRIMARY KEY (Group_ID);

CREATE SEQUENCE S_TCHG_OPERATION_GROUP INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу со всеми операциями из указателя

CREATE TABLE TCHG_OPERATION_LIST (
    Operation_ID        NUMBER          NOT NULL,
    Operation_Group_ID  NUMBER          NOT NULL,
    Operation_Number    NUMBER          NOT NULL,
    Operation_Name      VARCHAR2(1000)    NOT NULL
);

ALTER TABLE TCHG_OPERATION_LIST
    ADD CONSTRAINT C_Operation_ID_PK PRIMARY KEY (Operation_ID);
ALTER TABLE TCHG_OPERATION_LIST
    ADD CONSTRAINT C_Operation_Group_ID_FK FOREIGN KEY (Operation_Group_ID) REFERENCES TCHG_OPERATION_GROUP(Group_ID);

CREATE SEQUENCE S_TCHG_OPERATION_LIST INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу с технологическими процессами

CREATE TABLE TCHG_PROCESS (
    Process_ID      NUMBER          NOT NULL,
    Process_Note    VARCHAR2(1000)  NULL
);

ALTER TABLE TCHG_PROCESS
    ADD CONSTRAINT C_Process_ID_PK PRIMARY KEY (Process_ID);

CREATE SEQUENCE S_TCHG_PROCESS INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу оборудования

CREATE TABLE TCHG_TOOLS (
    Tool_ID     NUMBER          NOT NULL,
    Tool_Name   VARCHAR2(500)    NOT NULL
);

ALTER TABLE TCHG_TOOLS
    ADD CONSTRAINT C_Tool_ID_PK PRIMARY KEY (Tool_ID);

CREATE SEQUENCE S_TCHG_TOOLS INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу с технологическими операциями ТП

CREATE TABLE TCHG_PROCESS_OPERATION (
    Process_Operation_ID    NUMBER          NOT NULL,
    Process_ID              NUMBER          NOT NULL,
    GOST_Operation_ID       NUMBER          NOT NULL,
    Operation_About         VARCHAR2(500)   NOT NULL,
    Operation_Time          NUMBER          NOT NULL,
    Operation_Tools_ID      NUMBER          NOT NULL
);

ALTER TABLE TCHG_PROCESS_OPERATION
    ADD CONSTRAINT C_Process_Operation_ID_PK PRIMARY KEY (Process_Operation_ID);
ALTER TABLE TCHG_PROCESS_OPERATION
    ADD CONSTRAINT C_GOST_Operation_ID_FK FOREIGN KEY (GOST_Operation_ID) REFERENCES TCHG_OPERATION_LIST(Operation_ID);
ALTER TABLE TCHG_PROCESS_OPERATION
    ADD CONSTRAINT C_Process_ID_FK FOREIGN KEY (Process_ID) REFERENCES TCHG_PROCESS(Process_ID);
ALTER TABLE TCHG_PROCESS_OPERATION
    ADD CONSTRAINT C_Operation_Tools_ID_FK FOREIGN KEY (Operation_Tools_ID) REFERENCES TCHG_TOOLS(Tool_ID);

CREATE SEQUENCE S_TCHG_PROCESS_OPERATION INCREMENT BY 1 START WITH 1;

PROMPT Создаём публичные синонимы

DROP PUBLIC SYNONYM TCHG_OPERATION_GROUP;
CREATE PUBLIC SYNONYM TCHG_OPERATION_GROUP FOR TCHG_OPERATION_GROUP;

DROP PUBLIC SYNONYM TCHG_OPERATION_LIST;
CREATE PUBLIC SYNONYM TCHG_OPERATION_LIST FOR TCHG_OPERATION_LIST;

DROP PUBLIC SYNONYM TCHG_PROCESS;
CREATE PUBLIC SYNONYM TCHG_PROCESS FOR TCHG_PROCESS;

DROP PUBLIC SYNONYM S_TCHG_PROCESS;
CREATE PUBLIC SYNONYM S_TCHG_PROCESS FOR S_TCHG_PROCESS;

DROP PUBLIC SYNONYM TCHG_TOOLS;
CREATE PUBLIC SYNONYM TCHG_TOOLS FOR TCHG_TOOLS;

DROP PUBLIC SYNONYM S_TCHG_TOOLS;
CREATE PUBLIC SYNONYM S_TCHG_TOOLS FOR S_TCHG_TOOLS;

DROP PUBLIC SYNONYM TCHG_PROCESS_OPERATION;
CREATE PUBLIC SYNONYM TCHG_PROCESS_OPERATION FOR TCHG_PROCESS_OPERATION;

DROP PUBLIC SYNONYM S_TCHG_PROCESS_OPERATION;
CREATE PUBLIC SYNONYM S_TCHG_PROCESS_OPERATION FOR S_TCHG_PROCESS_OPERATION;


SPOOL off;
quit;