SPOOL log_temp.txt
PROMPT Модуль инженера конструктора
PROMPT Создаём таблицу устройств

CREATE TABLE ENG_DEVICE (
    Device_ID               NUMBER          NOT NULL,
    Device_Name             VARCHAR(255)    NOT NULL,
    Device_About            VARCHAR2(1000)  NOT NULL,
    Device_TechProcess_ID   NUMBER          NULL
);

ALTER TABLE ENG_DEVICE
    ADD CONSTRAINT C_Device_ID_PK PRIMARY KEY ( Device_ID );

CREATE SEQUENCE S_ENG_DEVICE INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу классов компонентов

CREATE TABLE ENG_COMPONENT_CLASS(
    Class_ID    NUMBER  NOT NULL,
    Class_Name  VARCHAR(25) NOT NULL
);

ALTER TABLE ENG_COMPONENT_CLASS
    ADD CONSTRAINT C_Class_ID_PK PRIMARY KEY (Class_ID);

CREATE SEQUENCE S_ENG_COMPONENT_CLASS INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу библиотеки компонентов

CREATE TABLE ENG_COMPONENT_LIB (
    Lib_Component_ID        NUMBER      NOT NULL,
    Component_Class_ID      NUMBER      NOT NULL,
    Component_PartNumber    VARCHAR(30) NOT NULL,
    Component_Instalation   VARCHAR(3)  NOT NULL,
    Component_Manufacturer  VARCHAR(30) NULL,
    Component_Count_Pad     NUMBER      NOT NULL
);

ALTER TABLE ENG_COMPONENT_LIB
    ADD CONSTRAINT C_Lib_Component_ID_PK PRIMARY KEY (Lib_Component_ID);
ALTER TABLE ENG_COMPONENT_LIB
    ADD CONSTRAINT C_Component_Class_ID_FK FOREIGN KEY (Component_Class_ID) REFERENCES ENG_COMPONENT_CLASS(Class_ID);
ALTER TABLE ENG_COMPONENT_LIB
    ADD CONSTRAINT C_Component_Instalation_CHK CHECK ( Component_Instalation = 'THT' OR Component_Instalation = 'SMD');

CREATE SEQUENCE S_ENG_COMPONENT_LIB INCREMENT BY 1 START WITH 1;

PROMPT Создаём таблицу компонентов устройств
CREATE TABLE ENG_COMPONENT (
    Component_ID            NUMBER      NOT NULL,
    Component_ID_in_Lib     NUMBER      NOT NULL,
    Component_Device_ID     NUMBER      NOT NULL,
    Component_Designator    VARCHAR(10) NOT NULL,
    Component_Nominal       VARCHAR(10) NULL
);

ALTER TABLE ENG_COMPONENT
    ADD CONSTRAINT C_Component_ID_PK PRIMARY KEY (Component_ID);
ALTER TABLE ENG_COMPONENT
    ADD CONSTRAINT C_Component_Device_ID_FK FOREIGN KEY (Component_Device_ID) REFERENCES ENG_DEVICE(Device_ID);
ALTER TABLE ENG_COMPONENT
    ADD CONSTRAINT C_Component_ID_in_Lib_FK FOREIGN KEY (Component_ID_in_Lib) REFERENCES ENG_COMPONENT_LIB(Lib_Component_ID);

CREATE SEQUENCE S_ENG_COMPONENT INCREMENT BY 1 START WITH 1;


PROMPT Создаём публичные синонимы

DROP PUBLIC SYNONYM ENG_DEVICE;
CREATE PUBLIC SYNONYM ENG_DEVICE FOR ENG_DEVICE;

DROP PUBLIC SYNONYM S_ENG_DEVICE;
CREATE PUBLIC SYNONYM S_ENG_DEVICE FOR S_ENG_DEVICE;

DROP PUBLIC SYNONYM ENG_COMPONENT_CLASS;
CREATE PUBLIC SYNONYM ENG_COMPONENT_CLASS FOR ENG_COMPONENT_CLASS;

DROP PUBLIC SYNONYM S_ENG_COMPONENT_CLASS;
CREATE PUBLIC SYNONYM S_ENG_COMPONENT_CLASS FOR S_ENG_COMPONENT_CLASS;

DROP PUBLIC SYNONYM ENG_COMPONENT;
CREATE PUBLIC SYNONYM ENG_COMPONENT FOR ENG_COMPONENT;

DROP PUBLIC SYNONYM S_ENG_COMPONENT;
CREATE PUBLIC SYNONYM S_ENG_COMPONENT FOR S_ENG_COMPONENT;

DROP PUBLIC SYNONYM ENG_COMPONENT_LIB;
CREATE PUBLIC SYNONYM ENG_COMPONENT_LIB FOR ENG_COMPONENT_LIB;

DROP PUBLIC SYNONYM S_ENG_COMPONENT_LIB;
CREATE PUBLIC SYNONYM S_ENG_COMPONENT_LIB FOR S_ENG_COMPONENT_LIB;

SPOOL off;
quit;