SPOOL log_temp.txt
PROMPT Модуль директора

PROMPT Создаём таблицу с задачами для пользователей

CREATE TABLE DIR_TASKS(
    Task_ID         NUMBER          NOT NULL,
    Task_User_ID    NUMBER          NOT NULL,
    Task_About      VARCHAR2(1000)  NOT NULL,
    Task_Check      NUMBER          NOT NULL
);

ALTER TABLE DIR_TASKS
    ADD CONSTRAINT C_Task_ID_PK PRIMARY KEY (Task_ID);
ALTER TABLE DIR_TASKS
    ADD CONSTRAINT C_Task_User_ID_FK FOREIGN KEY (Task_User_ID) REFERENCES AUTH_USERS(User_ID);

CREATE SEQUENCE S_DIR_TASKS INCREMENT BY 1 START WITH 1;

PROMPT Создаём публичные синонимы

DROP PUBLIC SYNONYM DIR_TASKS;
CREATE PUBLIC SYNONYM DIR_TASKS FOR DIR_TASKS;

DROP PUBLIC SYNONYM S_DIR_TASKS;
CREATE PUBLIC SYNONYM S_DIR_TASKS FOR S_DIR_TASKS;

SPOOL off;
quit;