SPOOL log_temp.txt
PROMPT Создаём пользователя для пользовательского общения с БД

DROP USER guest;
CREATE USER guest IDENTIFIED BY iu4;
GRANT CONNECT TO guest;
GRANT SELECT ON AUTH_USERS TO guest;
GRANT INSERT ON AUTH_USERS TO guest;
GRANT SELECT ON S_AUTH_USERS TO guest;
GRANT ALTER ON S_AUTH_USERS TO guest;

GRANT SELECT ON ENG_DEVICE TO guest;
GRANT SELECT ON ENG_COMPONENT_CLASS TO guest;
GRANT SELECT ON ENG_COMPONENT_LIB TO guest;
GRANT SELECT ON ENG_COMPONENT TO guest;
GRANT SELECT ON ENG_HELP_GOSTS TO guest;

GRANT SELECT ON TCHG_OPERATION_GROUP TO guest;
GRANT SELECT ON TCHG_OPERATION_LIST TO guest;
GRANT SELECT ON TCHG_PROCESS TO guest;
GRANT SELECT ON TCHG_TOOLS TO guest;
GRANT SELECT ON TCHG_PROCESS_OPERATION TO guest;

GRANT SELECT ON COM_TP_DEV TO guest;

PROMPT Создаём пользователя тех директора

DROP USER director;
CREATE USER director IDENTIFIED BY qpalzm;
GRANT CONNECT TO director;
GRANT SELECT ON AUTH_USERS TO director;

GRANT SELECT ON ENG_DEVICE TO director;
GRANT ALTER ON ENG_DEVICE TO director;
GRANT DELETE ON ENG_DEVICE TO director;
GRANT INSERT ON ENG_DEVICE TO director;

GRANT SELECT ON S_ENG_DEVICE TO director;
GRANT ALTER ON S_ENG_DEVICE TO director;

GRANT SELECT ON ENG_COMPONENT_CLASS TO director;

GRANT SELECT ON ENG_COMPONENT_LIB TO director;
GRANT ALTER ON ENG_COMPONENT_LIB TO director;
GRANT DELETE ON ENG_COMPONENT_LIB TO director;
GRANT INSERT ON ENG_COMPONENT_LIB TO director;

GRANT SELECT ON S_ENG_COMPONENT_LIB TO director;
GRANT ALTER ON S_ENG_COMPONENT_LIB TO director;

GRANT SELECT ON ENG_COMPONENT TO director;
GRANT ALTER ON ENG_COMPONENT TO director;
GRANT DELETE ON ENG_COMPONENT TO director;

GRANT SELECT ON S_ENG_COMPONENT TO director;
GRANT ALTER ON S_ENG_COMPONENT TO director;

GRANT SELECT ON ENG_HELP_GOSTS TO director;

GRANT SELECT ON TCHG_OPERATION_GROUP TO director;
GRANT SELECT ON TCHG_OPERATION_LIST TO director;
GRANT SELECT ON TCHG_PROCESS TO director;
GRANT SELECT ON TCHG_TOOLS TO director;
GRANT SELECT ON TCHG_PROCESS_OPERATION TO director;

GRANT SELECT ON TCHG_OPERATION_GROUP TO director;

GRANT SELECT ON TCHG_OPERATION_LIST TO director;

GRANT SELECT ON TCHG_PROCESS TO director;
GRANT ALTER ON TCHG_PROCESS TO director;
GRANT DELETE ON TCHG_PROCESS TO director;
GRANT INSERT ON TCHG_PROCESS TO director;

GRANT SELECT ON S_TCHG_PROCESS TO director;
GRANT ALTER ON S_TCHG_PROCESS TO director;

GRANT SELECT ON TCHG_TOOLS TO director;
GRANT ALTER ON TCHG_TOOLS TO director;
GRANT DELETE ON TCHG_TOOLS TO director;
GRANT INSERT ON TCHG_TOOLS TO director;

GRANT SELECT ON S_TCHG_TOOLS TO director;
GRANT ALTER ON S_TCHG_TOOLS TO director;

GRANT SELECT ON TCHG_PROCESS_OPERATION TO director;
GRANT ALTER ON TCHG_PROCESS_OPERATION TO director;
GRANT DELETE ON TCHG_PROCESS_OPERATION TO director;
GRANT INSERT ON TCHG_PROCESS_OPERATION TO director;

GRANT SELECT ON S_TCHG_PROCESS_OPERATION TO director;
GRANT ALTER ON S_TCHG_PROCESS_OPERATION TO director;

GRANT SELECT ON COM_TP_DEV TO director;
GRANT ALTER ON COM_TP_DEV TO director;
GRANT DELETE ON COM_TP_DEV TO director;
GRANT INSERT ON COM_TP_DEV TO director;

GRANT SELECT ON S_COM_TP_DEV TO director;
GRANT ALTER ON S_COM_TP_DEV TO director;

PROMPT Создаём пользователя технолога

DROP USER technologist;
CREATE USER technologist IDENTIFIED BY qwerty;
GRANT CONNECT TO technologist;
GRANT SELECT ON AUTH_USERS TO technologist;

GRANT SELECT ON ENG_DEVICE TO technologist;
GRANT DELETE ON ENG_DEVICE TO technologist;
GRANT INSERT ON ENG_DEVICE TO technologist;

GRANT SELECT ON ENG_COMPONENT_CLASS TO technologist;
GRANT SELECT ON ENG_COMPONENT_LIB TO technologist;
GRANT SELECT ON ENG_COMPONENT TO technologist;

GRANT SELECT ON ENG_HELP_GOSTS TO technologist;

GRANT SELECT ON TCHG_OPERATION_GROUP TO technologist;

GRANT SELECT ON TCHG_OPERATION_LIST TO technologist;

GRANT SELECT ON TCHG_PROCESS TO technologist;
GRANT ALTER ON TCHG_PROCESS TO technologist;
GRANT DELETE ON TCHG_PROCESS TO technologist;
GRANT INSERT ON TCHG_PROCESS TO technologist;

GRANT SELECT ON S_TCHG_PROCESS TO technologist;
GRANT ALTER ON S_TCHG_PROCESS TO technologist;

GRANT SELECT ON TCHG_TOOLS TO technologist;
GRANT ALTER ON TCHG_TOOLS TO technologist;
GRANT DELETE ON TCHG_TOOLS TO technologist;
GRANT INSERT ON TCHG_TOOLS TO technologist;

GRANT SELECT ON S_TCHG_TOOLS TO technologist;
GRANT ALTER ON S_TCHG_TOOLS TO technologist;

GRANT SELECT ON TCHG_PROCESS_OPERATION TO technologist;
GRANT ALTER ON TCHG_PROCESS_OPERATION TO technologist;
GRANT DELETE ON TCHG_PROCESS_OPERATION TO technologist;
GRANT INSERT ON TCHG_PROCESS_OPERATION TO technologist;

GRANT SELECT ON S_TCHG_PROCESS_OPERATION TO technologist;
GRANT ALTER ON S_TCHG_PROCESS_OPERATION TO technologist;

GRANT SELECT ON COM_TP_DEV TO technologist;
GRANT ALTER ON COM_TP_DEV TO technologist;
GRANT DELETE ON COM_TP_DEV TO technologist;
GRANT INSERT ON COM_TP_DEV TO technologist;

GRANT SELECT ON S_COM_TP_DEV TO technologist;
GRANT ALTER ON S_COM_TP_DEV TO technologist;

PROMPT Создаём пользователя инженера-конструктора
DROP USER engineer;
CREATE USER engineer IDENTIFIED BY ijhgfdsaw;
GRANT CONNECT TO engineer;
GRANT SELECT ON ENG_DEVICE TO engineer;
GRANT ALTER ON ENG_DEVICE TO engineer;
GRANT DELETE ON ENG_DEVICE TO engineer;
GRANT INSERT ON ENG_DEVICE TO engineer;

GRANT SELECT ON S_ENG_DEVICE TO engineer;
GRANT ALTER ON S_ENG_DEVICE TO engineer;

GRANT SELECT ON ENG_COMPONENT_CLASS TO engineer;

GRANT SELECT ON ENG_COMPONENT_LIB TO engineer;
GRANT ALTER ON ENG_COMPONENT_LIB TO engineer;
GRANT DELETE ON ENG_COMPONENT_LIB TO engineer;
GRANT INSERT ON ENG_COMPONENT_LIB TO engineer;

GRANT SELECT ON S_ENG_COMPONENT_LIB TO engineer;
GRANT ALTER ON S_ENG_COMPONENT_LIB TO engineer;

GRANT SELECT ON ENG_COMPONENT TO engineer;
GRANT ALTER ON ENG_COMPONENT TO engineer;
GRANT DELETE ON ENG_COMPONENT TO engineer;
GRANT INSERT ON ENG_COMPONENT TO engineer;

GRANT SELECT ON S_ENG_COMPONENT TO engineer;
GRANT ALTER ON S_ENG_COMPONENT TO engineer;

GRANT SELECT ON ENG_HELP_GOSTS TO engineer;

GRANT SELECT ON TCHG_OPERATION_GROUP TO engineer;
GRANT SELECT ON TCHG_OPERATION_LIST TO engineer;
GRANT SELECT ON TCHG_PROCESS TO engineer;
GRANT SELECT ON TCHG_TOOLS TO engineer;
GRANT SELECT ON TCHG_PROCESS_OPERATION TO engineer;

GRANT SELECT ON COM_TP_DEV TO engineer;

SPOOL off;
quit;