services:
  ais_sql_server:
    image: gvenzl/oracle-free:23
    container_name: ais_sql_server.g
    hostname: ais_sql_server.g
    restart: no
    networks:
      - internal
    ports:
      - 1521:1521
    volumes:
      - ./data:/opt/oracle/oradata
      - ./tables_setup/:/container-entrypoint-initdb.d
    environment:
      APP_USER: "root"
      APP_USER_PASSWORD: "root"
      ORACLE_PASSWORD: "root"
      NLS_LANG: "AMERICAN_CIS.UTF8"

  ais:
    build: flask_app
    container_name: ais.g
    hostname: ais.g
    networks:
      - internal
    ports:
      - 5001:80
    restart: no
    depends_on:
      - ais_sql_server

networks:
  internal:
    driver: bridge
