PROMPT Создаём пользователя для администрирования БД

DROP USER admin_user CASCADE;
CREATE USER admin_user IDENTIFIED BY root1;
GRANT CONNECT TO admin_user;
GRANT CREATE ANY TRIGGER TO admin_user;
GRANT CREATE ANY PROCEDURE TO admin_user;
GRANT ALTER ANY TRIGGER TO admin_user;
GRANT ALTER ANY PROCEDURE TO admin_user;
GRANT DROP ANY TRIGGER TO admin_user;
GRANT DROP ANY PROCEDURE TO admin_user;
GRANT EXECUTE ANY PROCEDURE TO admin_user;

GRANT CREATE ANY TABLE TO admin_user;
GRANT ALTER ANY TABLE TO admin_user;
GRANT DROP ANY TABLE TO admin_user;

GRANT CREATE ANY SEQUENCE TO admin_user;
GRANT ALTER ANY SEQUENCE TO admin_user;
GRANT DROP ANY SEQUENCE TO admin_user;

GRANT CREATE PUBLIC SYNONYM TO admin_user;
GRANT DROP PUBLIC SYNONYM TO admin_user;

ALTER USER admin_user QUOTA 500M ON users;
SPOOL off;
quit;
