CONNECT admin_user/root1;

PROMPT Таблицы для связи между модулями
PROMPT Создаём таблицу связи ТП и устройств

CREATE TABLE COM_TP_DEV (
    TPDEV_Link_ID   NUMBER  NOT NULL,
    TP_ID           NUMBER  NOT NULL,
    Dev_ID          NUMBER  NOT NULL
);

ALTER TABLE COM_TP_DEV
    ADD CONSTRAINT C_TPDEV_Link_ID_PK PRIMARY KEY (TPDEV_Link_ID);
ALTER TABLE COM_TP_DEV
    ADD CONSTRAINT C_TP_ID_FK FOREIGN KEY (TP_ID) REFERENCES TCHG_PROCESS(Process_ID);
ALTER TABLE COM_TP_DEV
    ADD CONSTRAINT C_Dev_ID_FK FOREIGN KEY (Dev_ID) REFERENCES ENG_DEVICE(Device_ID);

CREATE SEQUENCE S_COM_TP_DEV INCREMENT BY 1 START WITH 1;

PROMPT Создаём публичные синонимы

DROP PUBLIC SYNONYM COM_TP_DEV;
CREATE PUBLIC SYNONYM COM_TP_DEV FOR COM_TP_DEV;

DROP PUBLIC SYNONYM S_COM_TP_DEV;
CREATE PUBLIC SYNONYM S_COM_TP_DEV FOR S_COM_TP_DEV;

SPOOL off;
quit;
